variables:
  - group: var-pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# -----------------------------
# VALIDATE STAGE
# -----------------------------
- stage: Validate
  displayName: 'Validation'
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.6'
     
    - task: Bash@3
      displayName: 'Install Checkov'
      inputs:
        targetType: inline
        script: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
         checkov -d terraform
        displayName: 'Security Scan'


- stage: Plan
  displayName: Terraform 'Plan'
  dependsOn: Validate
  jobs:
    - job: Plan
      steps:
      - checkout: self

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        inputs:
          terraformVersion: '1.6.6'

      - task: AWSCLI@1
        inputs:
          awsCredentials: 'aws-ser-con'
          regionName: 'us-east-1'
          displayName: 'Authenticate to AWS'
          awsCommand: 'sts'
          awsSubCommand: 'get-caller-identity'
    
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
           export AWS_ACCESS_KEY_ID=$(AWS_Access_Key_ID)
           export AWS_SECRET_ACCESS_KEY=$(Secret_Access_Key)
           export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
           terraform init \
            -backend-config="bucket=$(s3_bucket)" \
            -backend-config="key=$(tfstate_key)" \
            -backend-config="region=$(aws_region)" \
            -backend-config="dynamodb_table=$(dynamodb_table)" \
            -backend-config="encrypt=true"
          displayName: 'Terraform Plan'

  
- stage: Apply
  displayName: Terraform 'Apply'
  dependsOn: Plan
  condition: succeeded()
  jobs:
    - job: Apply
      steps:
      - checkout: self

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        inputs:
          terraformVersion: '1.6.6'

      - task: AWSCLI@1
        inputs:
          awsCredentials: 'aws-ser-con'
          regionName: 'us-east-1'
          displayName: 'Authenticate to AWS'
          awsCommand: 'sts'
          awsSubCommand: 'get-caller-identity'
    
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
           export AWS_ACCESS_KEY_ID=$(AWS_Access_Key_ID)
           export AWS_SECRET_ACCESS_KEY=$(Secret_Access_Key)
           export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
           terraform init \
            -backend-config="bucket=$(s3_bucket)" \
            -backend-config="key=$(tfstate_key)" \
            -backend-config="region=$(aws_region)" \
            -backend-config="dynamodb_table=$(dynamodb_table)" \
            -backend-config="encrypt=true"
          terraform apply -auto-approve
          displayName: 'Terraform Apply'

