variables:
  - group: var-pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# -----------------------------
# VALIDATE STAGE
# -----------------------------
- stage: Validate
  displayName: 'Validation'
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.6'
     
    - task: Bash@3
      displayName: 'Install Checkov'
      inputs:
        targetType: inline
        script: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          checkov -d terraform
      displayName: 'Security Scan'  

- stage: Plan
  displayName: Terraform 'Plan'
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.6'
    
    # - script: |
    #    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #    unzip awscliv2.zip
    #    sudo ./aws/install
    #    aws --version
    #   displayName: Install AWS CLI v2

    - task: AWSCLI@1
      inputs:
        awsCredentials: 'aws-ser-con'
        regionName: 'us-east-1'
        displayName: 'Authenticate to AWS'
        awsCommand: 'sts'
        awsSubCommand: 'get-caller-identity'

    - script: |
        terraform init \
          -backend-config="bucket=my-terraform-state-bucket" \
          -backend-config="key=prod/afzal.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="dynamodb_table=terraform-lock-table" \
          -backend-config="encrypt=true"
      displayName: 'Terraform Init'

    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'

# - stage: Apply
#   displayName: Terraform 'Apply'
#   dependsOn: Plan
#   condition: succeeded()
#   jobs:
#   - job: Apply
#     steps:
#     - checkout: self

#     - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
#       inputs:
#         terraformVersion: '1.6.6'

#     - task: AWSCLI@1
#       inputs:
#         awsCredentials: 'aws-terraform-conn'
#         regionName: 'us-east-1'
#       displayName: 'Authenticate to AWS'

#     - script: |
#         terraform init \
#           -backend-config="bucket=my-terraform-state-bucket" \
#           -backend-config="key=prod/afzal.tfstate" \
#           -backend-config="region=us-east-1" \
#           -backend-config="dynamodb_table=terraform-lock-table" \
#           -backend-config="encrypt=true"
#       displayName: 'Terraform Init'

#     - script: terraform apply -auto-approve
#       displayName: 'Terraform Apply'
